### ISSUE TITLE
Tag master as new version so filecoin-ffi can use AMD cards

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/bellperson#101]
I've just tried to build `lotus` myself using the updated bellman repository - but this is the first time I'm touching rust, as you can see;
```
  Compiling filcrypto v0.7.4 (/home/filecoin/lotus/extern/filecoin-ffi/rust)
error[E0599]: no method named `name` found for enum `std::result::Result<fil_ocl::standard::platform::Platform, bellperson::gpu::error::GPUError>` in the current scope
  --> src/util/api.rs:41:54
   |
41 |         log::info!("Platform selected: {}", platform.name());
   |                                                      ^^^^ method not found in `std::result::Result<fil_ocl::standard::platform::Platform, bellperson::gpu::error::GPUError>`

error[E0308]: mismatched types
  --> src/util/api.rs:43:51
   |
43 |         let devicelist: Vec<Device> = get_devices(&platform).unwrap_or_default();
   |                                                   ^^^^^^^^^ expected struct `fil_ocl::standard::platform::Platform`, found enum `std::result::Result`
   |
   = note: expected reference `&fil_ocl::standard::platform::Platform`
              found reference `&std::result::Result<fil_ocl::standard::platform::Platform, bellperson::gpu::error::GPUError>`
```

So, if its not too much of a problem, it would be nice if this master branch has a new tag, so the new version can be used in `filecoin-ffi`, so that we can start testing AMD on Lotus :) 

Given I have 0 experience with rust  (well, apart from this disappointing try), I have no idea how hard this is..

Decided to just file an issue - in the meantime I will be learning a bit of rust to see if I can get this problem solved myself :)

Cheers!

**Comment by RobQuistNL** [comment]
Oh.. I've just seen the open PR's - I guess you're all hard at work doing exactly that what I've just tried (but better) :)

**Comment by dignifiedquire** [comment]
It took a while due to other issues, but we are on track on shipping a release that will include the amd code finally.

**Comment by vmx** [comment]
That was done a long time ago :)
