### ISSUE TITLE
Ability to run on Nvidia and AMD cards at the same time

### ISSUE THREAD

**Issue by Wondertan** [filecoin-project/bellperson#110]
## Background
While participating in the Spacerace I got an idea to use GPUs I have for ETH mining in order to accelerate FIL commitments. Then I started experimenting with this repo using __2080 TI__ and __RX 480__ at the same time. Unfortunately, it turned out that they work only separately. Finally, I saw a small note in [README_AMD](https://github.com/filecoin-project/bellman/blob/master/README_AMD.md#notes) telling that there was a failed attempt doing so but without any further information and it seems that no one ever tried to fix that. Hence, let this issue track the feature.

## Test run results
```
BELLMAN_CUSTOM_GPU='GeForce RTX 2080 Ti:4352, gfx803:2304'
BELLMAN_CPU_UTILIZATION=0
```
```
INFO  bellperson::gpu::locks GPU is available for Multiexp!
INFO  bellperson::gpu::utils Adding "GeForce RTX 2080 Ti" to GPU list with 4352 CUDA cores.
INFO  bellperson::gpu::utils Adding "gfx803" to GPU list with 2304 CUDA cores.
INFO  bellperson::gpu::multiexp Multiexp: 1 working device(s) selected. (CPU utilization: 0)
INFO  bellperson::gpu::multiexp Multiexp: Device 0: gfx803 (Chunk-size: 3964764)
INFO  bellperson::multiexp GPU Multiexp kernel instantiated!
```
As you can see from the logs above, Bellman successfully detected both GPUs but selected only one device😞

**Comment by jleni** [comment]
This should be easy to fix. The instability I had when mixing was related to device drivers.. Still, I don't think RX480 will contribute much. It would be different if you were mixing two top of the line boards in my opinion.

**Comment by Wondertan** [comment]
> It would be different if you were mixing two top of the line boards in my opinion.

Have you tried or do you propose buying a new GPU as the solution?😄

**Comment by Wondertan** [comment]
> The instability I had when mixing was related to device drivers

I was using latest drivers for both cards.

**Comment by Wondertan** [comment]
> Still, I don't think RX480 will contribute much

Too subjective, while possible real numbers outcome from the working above setup - not.

**Comment by jleni** [comment]
it is not extremely subjective.. it is a bit of an informed comment. We could eventually try it.. 
The memory bandwidth and compute capability of the two boards is very different. If you split the computation, it is very likely that RTX480 will end up slowing down things. 
It is still possible to try, but I am giving you an opinion based on previous experiences.

**Comment by vmx** [comment]
There are currently no plans to support such a hybrid environment, hence I'm closing this issue.
