### ISSUE TITLE
 GPU FFT failed! Error: Ocl Error on GeForce RTX 3080

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/bellperson#111]
[original issue](https://github.com/filecoin-project/lotus/issues/3948#issue-706058872)  by @nickboot

**Describe the bug**
GeForce RTX 3080，GPU FFT failed! Falling back to CPU 

**To Reproduce**
1. nvidia-smi -L
GPU 0: GeForce RTX 3080
2. export BELLMAN_CUSTOM_GPU="GeForce RTX 3080:8704"
3. lotus-bench sealing --storage-dir=/benchtmp --sector-size=32GiB --num-sectors=2 --parallel=2 

**Screenshots**
2020-09-22T03:20:30.079 INFO filecoin_proofs::api::seal > seal_commit_phase2:start
2020-09-22T03:20:30.079 INFO filecoin_proofs::caches > trying parameters memory cache for: STACKED[34359738368]
2020-09-22T03:20:30.079 INFO filecoin_proofs::caches > no params in memory cache for STACKED[34359738368]
2020-09-22T03:20:32.249 INFO filecoin_proofs::api::seal > got groth params (34359738368) while sealing
2020-09-22T03:20:32.249 INFO filecoin_proofs::api::seal > snark_proof:start
2020-09-22T03:20:32.259 INFO bellperson::groth16::prover > Bellperson 0.9.2 is being used!
2020-09-22T03:22:32.470 TRACE storage_proofs_porep::stacked::vanilla::proof > processing config 1/8 with column nodes 217728
2020-09-22T03:22:46.683 TRACE storage_proofs_porep::stacked::vanilla::proof > base data len 134217728, tree data len 19173961
2020-09-22T03:22:46.683 INFO storage_proofs_porep::stacked::vanilla::proof > persisting base tree_c 1/8 of length 153391689
2020-09-22T03:22:46.683 TRACE storage_proofs_porep::stacked::vanilla::proof > flattening tree_c base data of 134217728 nodes using batch size 262144
2020-09-22T03:22:48.782 TRACE storage_proofs_porep::stacked::vanilla::proof > done flattening tree_c base data
2020-09-22T03:22:48.782 TRACE storage_proofs_porep::stacked::vanilla::proof > flattening tree_c tree data of 19173961 nodes using batch size 262144 and base offset 134217728
2020-09-22T03:22:49.113 TRACE storage_proofs_porep::stacked::vanilla::proof > done flattening tree_c tree data
2020-09-22T03:22:49.113 TRACE storage_proofs_porep::stacked::vanilla::proof > writing tree_c store data
2020-09-22T03:22:49.652 TRACE storage_proofs_porep::stacked::vanilla::proof > done writing tree_c store data
2020-09-22T03:26:37.792 INFO bellperson::gpu::locks > GPU is available for FFT!
2020-09-22T03:26:37.798 DEBUG bellperson::gpu::locks > Acquiring GPU lock...
2020-09-22T03:26:37.798 DEBUG bellperson::gpu::locks > GPU lock acquired!
2020-09-22T03:26:41.586 INFO bellperson::gpu::fft > FFT: 1 working device(s) selected.
2020-09-22T03:26:41.586 INFO bellperson::gpu::fft > FFT: Device 0: GeForce RTX 3080
2020-09-22T03:26:41.586 INFO bellperson::domain > GPU FFT kernel instantiated!
2020-09-22T03:27:05.456 WARN bellperson::gpu::locks > GPU FFT failed! Falling back to CPU... Error: Ocl Error:

################################ OPENCL ERROR ###############################

Error executing function: clEnqueueNDRangeKernel("radix_fft")

Status error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)

Please visit the following url for more information:

https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors

#############################################################################

2020-09-22T03:27:53.186 WARN bellperson::gpu::locks > GPU FFT failed! Falling back to CPU... Error: Ocl Error:

################################ OPENCL ERROR ###############################

Error executing function: clEnqueueNDRangeKernel("radix_fft")

Status error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)

Please visit the following url for more information:

https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors

#############################################################################
**Version (run `lotus version`):**
lotus-bench version 0.7.1

**Comment by jennijuju** [comment]
form `Jinbin` : 2 sector need 16GB, GTX 3080 only have 10GB.

**Comment by RobQuistNL** [comment]
the `--num-sectors=2 --parallel=2` only apply to PC1 in the benchmarks if I'm not mistaken

**Comment by gavin-ygy** [comment]
lotus-worker ( version: 1.10.0-rc2+mainnet+git.8f426b49e.dirty )
GPU: 3080
GPU driver:  460.80
At first, the worker do P2 normally . But after  finish a few P2 tasks,  it reports: 
----------
thread '<unnamed>' panicked at 'failed to add columns: GPUError("Ocl(\n\n################################ OPENCL ERROR ############################### \n\nError executing function: clEnqueueWriteBuffer  \n\nStatus error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)  \n\nPlease visit the following url for more information: \n\nhttps://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueWriteBuffer.html#errors  \n\n############################################################################# \n)")', /home/vm/test/test-v1.11/storage-proofs-porep-8.0.0/src/stacked/vanilla/proof.rs:578:38
stack backtrace:
   0:          0x248bfe0 - std::backtrace_rs::backtrace::libunwind::trace::hdcf4f90f85129e83
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:          0x248bfe0 - std::backtrace_rs::backtrace::trace_unsynchronized::h2669e30cb82f6732
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:          0x248bfe0 - std::sys_common::backtrace::_print_fmt::hfbda19e17f6db318
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/sys_common/backtrace.rs:67:5
   3:          0x248bfe0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1a8751bf59281272
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/sys_common/backtrace.rs:46:22
   4:          0x24fc24f - core::fmt::write::h7aa6cd0067dca82a
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/core/src/fmt/mod.rs:1094:17
   5:          0x2480775 - std::io::Write::write_fmt::hd7dd3a1df9b6befb
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/io/mod.rs:1580:15
   6:          0x248fd3b - std::sys_common::backtrace::_print::h551e9ec8a9fa8106
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/sys_common/backtrace.rs:49:5
   7:          0x248fd3b - std::sys_common::backtrace::print::ha4b1c5e95fa040b3
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/sys_common/backtrace.rs:36:9
   8:          0x248fd3b - std::panicking::default_hook::{{closure}}::h0b34c9ab7fb9f857
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/panicking.rs:208:50
   9:          0x248f81d - std::panicking::default_hook::h3067e8318decd17a
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/panicking.rs:225:9
  10:          0x249042d - std::panicking::rust_panic_with_hook::h81b8facc50f34daa
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/panicking.rs:591:17
  11:          0x2490027 - std::panicking::begin_panic_handler::{{closure}}::ha376ab85d95a000e
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/panicking.rs:497:13
  12:          0x248c49c - std::sys_common::backtrace::__rust_end_short_backtrace::h6795c8afdd1a77e6
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/sys_common/backtrace.rs:141:18
  13:          0x248ff89 - rust_begin_unwind
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/panicking.rs:493:5
  14:           0x5478a1 - core::panicking::panic_fmt::hbe99dddd3092ba3c
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/core/src/panicking.rs:92:14
  15:           0x547993 - core::result::unwrap_failed::hf79563fef9d11ab8
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/core/src/result.rs:1355:5
  16:          0x19a7a2c - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h6a05be3b72ec37ef
  17:          0x185676e - std::panicking::try::hb3f2e3e447aca7fb
  18:          0x1938765 - <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute::h380ad5885b158bf6
  19:           0x542d61 - rayon_core::registry::WorkerThread::wait_until_cold::hed0f6cc2c39f23d9
  20:          0x241a264 - rayon_core::registry::ThreadBuilder::run::h5db5f3f2e7341c44
  21:          0x26571f3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h63be1616c7fbf247
  22:          0x2420370 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1479dad92d037f1f
  23:          0x249eef7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3aa31cb6360b59d9

**Comment by gavin-ygy** [comment]
I guess the rust-fil-proofs v8.0.1 has GPU memory leaking when prossing P2 .Because the same machines works well with lotus-worker version v1.8-release (rust-fil-proofs v5.4.0).

**Comment by vmx** [comment]
For anyone who has a closer look, this is rust-fil-proofs v8.0.**0** and not v8.0.**1**, in case that matters (see the log line: `/home/vm/test/test-v1.11/storage-proofs-porep-8.0.0/src/stacked/vanilla/proof.rs:578:38`)

**Comment by gavin-ygy** [comment]
Sorry,  the v1.11  and v1.10 has the similar issue,  I confused the log.

**Comment by gavin-ygy** [comment]
Sorry,  the v1.11  and v1.10 has the similar issue,  I confused the log.

**Comment by gavin-ygy** [comment]
Sorry,  the v1.11  and v1.10 has the similar issue,  I confused the log.

**Comment by vmx** [comment]
As there aren't any recent reports of this issue, hence I expect it to be fixed. If it's still an issue, please re-open this issue and provide additional details.
