### ISSUE TITLE
BELLMAN0.10.0

### ISSUE THREAD

**Issue by ocean00** [filecoin-project/bellperson#118]
error[E0432]: unresolved import `bellperson::GPU_NVIDIA_DEVICES`
 --> src/util/api.rs:6:5
  |
6 | use bellperson::GPU_NVIDIA_DEVICES;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `GPU_NVIDIA_DEVICES` in the root

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `filcrypto`.

To learn more, run the command again with --verbose.
+ rm -f /tmp/tmp.PI50JUvXrk
make[1]: *** [Makefile:11: .install-filcrypto] Error 101
make[1]: Leaving directory '/lotus/extern/filecoin-ffi'
make: *** [Makefile:37: build/.filecoin-install] Error 2

**Comment by ocean00** [comment]
unresolved import `bellperson::GPU_NVIDIA_DEVICES`

**Comment by dignifiedquire** [comment]
This api is not available anymore, as now there are both nvidia and amd cards support on 0.10. You can take a look at https://github.com/filecoin-project/filecoin-ffi/pull/140/files  to see how you can replace that api
