### ISSUE TITLE
v0.9.3 build err

### ISSUE THREAD

**Issue by RustMan88** [filecoin-project/bellperson#119]
~/Workspace/RustProject/bellman$ cargo build
   Compiling bellperson v0.9.3 (/mnt/e/Workspace/RustProject/bellman)
error[E0309]: the parameter type `F` may not live long enough
  --> src/multicore.rs:68:25
   |
57 |         pub fn scope<'a, F, R>(&self, elements: usize, f: F) -> R
   |                          - help: consider adding an explicit lifetime bound `F: 'a`...
...
68 |             THREAD_POOL.scope(|scope| f(scope, chunk_size))
   |                         ^^^^^
   |
note: ...so that the type `[closure@src/multicore.rs:68:31: 68:59 f:F, chunk_size:&usize]` will meet its required lifetime bounds
  --> src/multicore.rs:68:25
   |
68 |             THREAD_POOL.scope(|scope| f(scope, chunk_size))
   |                         ^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0309`.
error: could not compile `bellperson`.

To learn more, run the command again with --verbose.

**Comment by viking2015** [comment]
fix err :

`pub fn scope<'a, F: 'a, R>(&self, elements: usize, f: F) -> R
            where
                F: FnOnce(&rayon::Scope<'a>, usize) -> R + Send,
                R: Send,
        {
            let chunk_size = if elements < *NUM_CPUS {
                1
            } else {
                elements / *NUM_CPUS
            };

            THREAD_POOL.scope(move |scope| f(scope, chunk_size))
        }`

**Comment by dignifiedquire** [comment]
What rust version are you using? all our ci compiles this code, so this should not be needed on a recent version

**Comment by rust-andy** [comment]
rust 1.47.0




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ddorgan"<notifications@github.com&gt;; 
发送时间: 2020年10月30日(星期五) 凌晨4:27
收件人: "filecoin-project/bellperson"<bellperson@noreply.github.com&gt;; 
抄送: "忍者小虾"<moyuan25@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [filecoin-project/bellperson] v0.9.3 build err (#119)





 
What rust version are you using? all our ci compiles this code, so this should not be needed on a recent version

**Comment by xcshuan** [comment]
@dignifiedquire @rust-andy Same question and my rust's version is 1.47 too.

**Comment by xcshuan** [comment]
![image](https://user-images.githubusercontent.com/24284441/99338860-005f2780-28c0-11eb-9758-a3ca037a532f.png)

**Comment by xcshuan** [comment]
![image](https://user-images.githubusercontent.com/24284441/99338860-005f2780-28c0-11eb-9758-a3ca037a532f.png)
![Uploading image.png…]()

**Comment by xcshuan** [comment]
![image](https://user-images.githubusercontent.com/24284441/99339961-09e98f00-28c2-11eb-993a-87062c6d7a5d.png)

**Comment by dignifiedquire** [comment]
Can you try with 1.46 please, and is it 1.47 stable or nightly?

**Comment by dignifiedquire** [comment]
oh and what `features` are enabled?

**Comment by xcshuan** [comment]
I don't know what features cause this, I can't compile storage-proofs 5.3.0 or 5.4.0 using `cargo`, but I can compile lotus based on storage-proofs 5.3.0 using `make clean all`, and the newest rust-proof-proofs master branch is compilable.

**Comment by vmx** [comment]
As the last comment indicates, master was working. I don't think there's a point looking into getting a two years old version compiled.
