### ISSUE TITLE
Error executing function: clBuildProgram (CL_NV_INVALID_MEM_ACCESS)

### ISSUE THREAD

**Issue by vmx** [filecoin-project/bellperson#135]
There are warning printed when running with the gpu feature enabled on the CI. It seems to still use the GPU for groth16. The errors come from the `domain` module. Here's an example run: https://app.circleci.com/pipelines/github/filecoin-project/bellperson/802/workflows/717fea32-85d2-40d8-bde8-4abc58107759/jobs/3452/parallel-runs/0/steps/0-108

```
[2020-12-16T13:01:03Z WARN  bellperson::domain] Cannot instantiate GPU FFT kernel! Error: OpenCL Error: Ocl Error: 
    
    ################################ OPENCL ERROR ############################### 
    
    Error executing function: clBuildProgram  
    
    Status error code: CL_NV_INVALID_MEM_ACCESS (-9999)  
    
    Please visit the following url for more information: 
    
    https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clBuildProgram.html#errors  
    
    ############################################################################# 
```

**Comment by sbwtw** [comment]
bellperson::gpu::multiexp::MultiexpKernel<E>::create returns error, maybe opencl error.

**Comment by vmx** [comment]
We've switched to a different OpenCL library, hence I expect this not being an issue anymore. I didn't see it occurring again.
