### ISSUE TITLE
[arm64 server] GPU failed, Error: Ocl Error: OPENCL ERROR

### ISSUE THREAD

**Issue by billy-chen-2019** [filecoin-project/bellperson#143]
Describe the bug
[arm64 server] GPU FFT failed! Falling back to CPU... Error: Ocl Error: OPENCL ERROR

[arm64 server] To Reproduce( )

Run './bench sealing --sector-size=512M'
See error
################################ OPENCL ERROR ###############################

Error executing function: clCreateProgramWithBinary

Status error code: CL_INVALID_VALUE (-30)

Please visit the following url for more information:

https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clCreateProgramWithBinary.html#errors

#############################################################################

**Comment by vmx** [comment]
Since this bug was reported, we've switched the underlying OpenCL library we are using. Hence I expect that this is not an issue anymore. If it still is an issue, please re-open this bug report with additional information.
