### ISSUE TITLE
Restrict gpu features to machines with a supported GPU

### ISSUE THREAD

**Issue by vmx** [filecoin-project/bellperson#151]
This is more of a proposal.

Currently if you compile bellperson with a the `gpu` feature enabled there is a fallback to use the CPU instead. Though even today that doesn't always work. For example if I run `cargo test --no-default-features --features blst,gpu` locally (I don't have a supported GPU) I get

```
failures:

---- domain::tests::gpu_fft_consistency stdout ----
thread 'domain::tests::gpu_fft_consistency' panicked at 'Cannot initialize kernel!: Simple("No working GPUs found!")', src/domain.rs:597:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    domain::tests::gpu_fft_consistency
```

Hence I propose that running this library with the `gpu` flag enabled is not supported if you don't have a supported GPU. This should reduce the maintenance work.

To make this more explicit I propose adding an early error (e.g. when trying to access the GPU the first time), that clearly states that you need a supported GPU.

**Comment by dignifiedquire** [comment]
I don't think this is the right solution. Downstream consumers often build with gpu flags enabled, expecting to be able to run on both gpu and non gpu systems. Adding the "gpu" features should simply be additional, and not remove anything.

**Comment by vmx** [comment]
The problem is that the GPU code path is quite different from the CPU one. Currently we have three code paths, CPU, GPU and GPU without a working GPU. So running the GPU code path without a GPU adds a source for bugs.

**Comment by dignifiedquire** [comment]
I understand that it is more complicated, but it is a relied upon feature which we should not remove just because it is simpler. Changing compile time options is non trivial for downstream consumers of eg Lotus

**Comment by vmx** [comment]
Would it them perhaps make sense to remove the pure CPU code path?

**Comment by dignifiedquire** [comment]
No, we still need to be able to compile without opencl installed

**Comment by vmx** [comment]
I had hoped we could reduce complexity rather then increasing it. But at least it's now clear to me that it is essential and not accidental complexity.
