### ISSUE TITLE
Test compatibility between paired and blstrs

### ISSUE THREAD

**Issue by nikkolasg** [filecoin-project/bellperson#161]
@cryptonemo @dignifiedquire

**Comment by cryptonemo** [comment]
Related work: https://github.com/filecoin-project/bellperson/pull/144/files/7092c75f8f2ffaaf0ddfea62e195e04fe76dcde3..7d2887da486ce6d1ae6495d2deafef2056de5127

**Comment by cryptonemo** [comment]
Resolved by #162
