### ISSUE TITLE
Benchmark FFT and multiexp

### ISSUE THREAD

**Issue by BoyuanFeng** [filecoin-project/bellperson#192]
### 1. Is there any official benchmark code for FFT on GPU?

There is a one-line code for benchmarking multiexp on GPU 

```RUST_LOG=info cargo test --features gpu -- --exact multiexp::gpu_multiexp_consistency --nocapture```

It shows that GPU is around 120x faster than the cpu version, when tested on a 3090 GPU.

Where can I find a similar one-line code for benchmarking FFT on GPU?

### 2. What is the maximum number of constraints supported?

As mentioned in the README, there is a certain upper bound on proof size (i.e., the number of constraints).

> Depending on the size of the proof being passed to the gpu for work, certain cards will not be able to allocate enough memory to either the FFT or Multiexp kernel.

While this number certainly depends on the GPU card, is there any rough number (e.g., $2^20$ constraints) for a 10GB GPU?

### 3. Multi-GPU for FFT and multiexp

Currently, could multi-gpu be used to support a larger size when out-of-memory?
It seems the current implementation use each GPU independently for many small-size FFT and multiexp, according to [fft.cl](https://github.com/filecoin-project/bellperson/blob/master/src/gpu/fft/fft.cl) and [multiexp.cl](https://github.com/filecoin-project/bellperson/blob/master/src/gpu/multiexp/multiexp.cl).

Thanks!

**Comment by BoyuanFeng** [comment]
I found ***domain::tests::gpu_fft_consistency*** provides the benchmark for fft. However, it failed on 3090 GPU since the computation results on GPU is different from the computation results on CPU.
***groth16::proof::test_with_bls12_381::serialization*** also failed.

All other tests passed.

I am wondering if the developers also observe these two failed tests, or it is something on my configuration. Thanks!

All results are collected on a 3090 GPU. The command is 

```
RUST_LOG=info cargo test --features gpu
```

The log is:

```
    Finished test [unoptimized + debuginfo] target(s) in 0.09s
     Running target/debug/deps/bellperson-4655600b2d93e83f

running 72 tests
test gadgets::boolean::test::test_allocated_bit ... ok
test gadgets::boolean::test::test_and_not ... ok
test gadgets::boolean::test::test_alloc_conditionally ... ok
test gadgets::boolean::test::test_and ... ok
test gadgets::boolean::test::test_boolean_negation ... ok
test gadgets::boolean::test::test_boolean_and ... ok
test gadgets::boolean::test::test_boolean_xor ... ok
test gadgets::boolean::test::test_field_into_allocated_bits_le ... ok
test gadgets::boolean::test::test_nor ... ok
test gadgets::boolean::test::test_enforce_equal ... ok
test gadgets::boolean::test::test_u64_into_boolean_vec_le ... ok
test gadgets::boolean::test::test_xor ... ok
test gadgets::boolean::test::test_boolean_sha256_ch ... ok
test gadgets::lookup::test::test_synth ... ok
[2021-06-04T21:56:18Z INFO  bellperson::gpu::utils] Device: Device { brand: Nvidia, name: "NVIDIA GeForce RTX 3090", memory: 25447170048, bus_id: Some(179), platform: Platform(PlatformId(0x7f59ec02d6f0)), device: Device(DeviceId(0x7f59ec036840)) }
test gadgets::boolean::test::test_boolean_sha256_maj ... ok
test gadgets::lookup::test::test_lookup3_xy ... ok
test gadgets::lookup::test::test_lookup3_xy_with_conditional_negation ... ok
test gadgets::num::test::test_allocated_num ... ok
test gadgets::num::test::test_num_conditional_reversal ... ok
test gadgets::num::test::test_num_multiplication ... ok
test gadgets::num::test::test_num_nonzero ... ok
test gadgets::num::test::test_num_scale ... ok
test gadgets::num::test::test_num_squaring ... ok
test gadgets::num::test::test_into_bits_strict ... ok
test domain::fft_composition ... ok
[2021-06-04T21:56:18Z INFO  bellperson::gpu::fft] FFT: 1 working device(s) selected.
[2021-06-04T21:56:18Z INFO  bellperson::gpu::fft] FFT: Device 0: NVIDIA GeForce RTX 3090
test domain::tests::gpu_fft_consistency ... FAILED
test gadgets::test::test_cs ... ok
test domain::parallel_fft_consistency ... ok
test gadgets::blake2s::test::test_blake2s_constant_constraints ... ok
test gadgets::uint32::test::test_uint32_from_bits ... ok
test gadgets::blake2s::test::test_blank_hash ... ok
test gadgets::uint32::test::test_uint32_rotr ... ok
test gadgets::uint32::test::test_uint32_from_bits_be ... ok
test gadgets::sha256::test::test_blank_hash ... ok
test gadgets::uint32::test::test_uint32_addmany_constants ... ok
test gadgets::uint32::test::test_uint32_shr ... ok
[2021-06-04T21:56:19Z INFO  bellperson::gpu::utils] Device: Device { brand: Nvidia, name: "NVIDIA GeForce RTX 3090", memory: 25447170048, bus_id: Some(179), platform: Platform(PlatformId(0x7f59ec02d6f0)), device: Device(DeviceId(0x7f59ec036840)) }
test gpu::utils::test_list_devices ... ok
test gadgets::blake2s::test::test_blake2s_precomp_constraints ... ok
test gadgets::sha256::test::test_full_block ... ok
test gadgets::blake2s::test::test_blake2s_constraints ... ok
test groth16::aggregate::proof::tests::test_proof_check ... ok
test groth16::aggregate::accumulator::test::test_pairing_randomize ... ok
test groth16::aggregate::proof::tests::test_proof_io ... ok
test groth16::aggregate::transcript::test::test_transcript ... ok
test groth16::aggregate::commit::tests::test_commit_single ... ok
test groth16::aggregate::commit::tests::test_commit_pair ... ok
test gadgets::uint32::test::test_uint32_sha256_ch ... ok
test groth16::proof::test_with_bls12_381::test_size ... ok
test groth16::prover::tests::test_proving_assignment_extend ... ok
test multicore::tests::test_log2_floor ... ok
[2021-06-04T21:56:25Z INFO  bellperson::gpu::utils] Device: Device { brand: Nvidia, name: "NVIDIA GeForce RTX 3090", memory: 25447170048, bus_id: Some(179), platform: Platform(PlatformId(0x7f59ec02d6f0)), device: Device(DeviceId(0x7f59ec036840)) }
test groth16::aggregate::srs::test::test_srs_invalid_length ... ok
test gadgets::uint32::test::test_uint32_sha256_maj ... ok
test multiexp::tests::test_extend_density_input ... ok
test multiexp::tests::test_extend_density_regular ... ok
test tests::test_add_simplify ... ok
test util_cs::test_cs::tests::test_compute_path ... ok
test util_cs::test_cs::tests::test_cs ... ok
test gadgets::uint32::test::test_uint32_xor ... ok
[2021-06-04T21:56:28Z INFO  bellperson::groth16::prover] Bellperson 0.14.0 is being used!
[2021-06-04T21:56:28Z INFO  bellperson::groth16::prover] starting proof timer
[2021-06-04T21:56:28Z INFO  bellperson::gpu::locks] GPU is available for FFT!
[2021-06-04T21:56:28Z INFO  bellperson::gpu::fft] FFT: 1 working device(s) selected.
[2021-06-04T21:56:28Z INFO  bellperson::gpu::fft] FFT: Device 0: NVIDIA GeForce RTX 3090
[2021-06-04T21:56:28Z INFO  bellperson::domain] GPU FFT kernel instantiated!
[2021-06-04T21:56:28Z INFO  bellperson::gpu::locks] GPU is available for Multiexp!
[2021-06-04T21:56:28Z WARN  bellperson::gpu::utils] Number of CUDA cores for your device (NVIDIA GeForce RTX 3090) is unknown! Best performance is only achieved when the number of CUDA cores is known! You can find the instructions on how to support custom GPUs here: https://lotu.sh/en+hardware-mining
[2021-06-04T21:56:28Z INFO  bellperson::gpu::multiexp] Multiexp: 1 working device(s) selected. (CPU utilization: 0)
[2021-06-04T21:56:28Z INFO  bellperson::gpu::multiexp] Multiexp: Device 0: NVIDIA GeForce RTX 3090 (Chunk-size: 4405294)
[2021-06-04T21:56:28Z INFO  bellperson::multiexp] GPU Multiexp kernel instantiated!
test gadgets::uint32::test::test_uint32_addmany ... ok
[2021-06-04T21:56:29Z INFO  bellperson::groth16::prover] prover time: 999.056574ms
test groth16::proof::test_with_bls12_381::serialization ... FAILED
test gadgets::blake2s::test::test_blake2s_256_vars ... ok
[2021-06-04T21:56:37Z INFO  bellperson::gpu::locks] GPU is available for Multiexp!
[2021-06-04T21:56:37Z WARN  bellperson::gpu::utils] Number of CUDA cores for your device (NVIDIA GeForce RTX 3090) is unknown! Best performance is only achieved when the number of CUDA cores is known! You can find the instructions on how to support custom GPUs here: https://lotu.sh/en+hardware-mining
[2021-06-04T21:56:37Z INFO  bellperson::gpu::multiexp] Multiexp: 1 working device(s) selected. (CPU utilization: 0)
[2021-06-04T21:56:37Z INFO  bellperson::gpu::multiexp] Multiexp: Device 0: NVIDIA GeForce RTX 3090 (Chunk-size: 4405294)
[2021-06-04T21:56:37Z INFO  bellperson::multiexp] GPU Multiexp kernel instantiated!
test gadgets::blake2s::test::test_blake2s_700_vars ... ok
test multiexp::gpu_multiexp_consistency ... ok
test domain::polynomial_arith ... test domain::polynomial_arith has been running for over 60 seconds
test gadgets::blake2s::test::test_blake2s ... test gadgets::blake2s::test::test_blake2s has been running for over 60 seconds
test gadgets::blake2s::test::test_blake2s_test_vectors ... test gadgets::blake2s::test::test_blake2s_test_vectors has been running for over 60 seconds
test gadgets::multipack::test_multipacking ... test gadgets::multipack::test_multipacking has been running for over 60 seconds
test gadgets::num::test::test_into_bits ... test gadgets::num::test::test_into_bits has been running for over 60 seconds
test gadgets::sha256::test::test_against_vectors ... test gadgets::sha256::test::test_against_vectors has been running for over 60 seconds
test groth16::multiscalar::tests::test_multiscalar_par ... test groth16::multiscalar::tests::test_multiscalar_par has been running for over 60 seconds
test groth16::multiscalar::tests::test_multiscalar_single ... test groth16::multiscalar::tests::test_multiscalar_single has been running for over 60 seconds
test multiexp::test_with_bls12 ... test multiexp::test_with_bls12 has been running for over 60 seconds
test gadgets::multipack::test_multipacking ... ok
test domain::polynomial_arith ... ok
test gadgets::blake2s::test::test_blake2s_test_vectors ... ok
test groth16::multiscalar::tests::test_multiscalar_par ... ok
test groth16::multiscalar::tests::test_multiscalar_single ... ok
test gadgets::num::test::test_into_bits ... ok
test gadgets::blake2s::test::test_blake2s ... ok
test gadgets::sha256::test::test_against_vectors ... ok
test multiexp::test_with_bls12 ... ok

failures:

---- domain::tests::gpu_fft_consistency stdout ----
Testing FFT for 2 elements...
GPU took 0ms.
CPU (16 cores) took 0ms.
Speedup: xNaN
thread 'domain::tests::gpu_fft_consistency' panicked at 'assertion failed: v1.coeffs == v2.coeffs', src/domain.rs:628:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- groth16::proof::test_with_bls12_381::serialization stdout ----
thread 'groth16::proof::test_with_bls12_381::serialization' panicked at 'assertion failed: verify_proof(&pvk, &proof, &[c]).unwrap()', src/groth16/proof.rs:283:13


failures:
    domain::tests::gpu_fft_consistency
    groth16::proof::test_with_bls12_381::serialization

test result: FAILED. 70 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
```

**Comment by BoyuanFeng** [comment]
1. gpu_fft_consistency passed on v100 gpu. It failed on 3090.

Not sure whether there are some hyperparameters breaks when switching from V100 to 3090.
It would be great if this can be fixed on Ampere GPUs such as 3090.

2. On V100 with 16 GB memory, gpu_fft can support at most 2^26 size, and would be out-of-memory (i.e., CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)) when processing 2^27 size.

**Comment by cszz12** [comment]
you can add some panic info to detect GPU execution errors, GPU must have failed in your situation

**Comment by ApxToTop** [comment]
> ### 1.GPU上有没有官方的FFT基准代码？
> 有一行代码用于在 GPU 上对 multiexp 进行基准测试
> 
> `RUST_LOG=info cargo test --features gpu -- --exact multiexp::gpu_multiexp_consistency --nocapture`
> 
> 它表明，在 3090 GPU 上测试时，GPU 比 cpu 版本快 120 倍左右。
> 
> 在哪里可以找到类似的单行代码，用于在 GPU 上对 FFT 进行基准测试？
> 
> ### 2. 支持的最大约束数是多少？
> 正如自述文件中提到的，证明大小（即约束的数量）有一定的上限。
> 
> > 根据传递给 gpu 进行工作的证明的大小，某些卡将无法为 FFT 或 Multiexp 内核分配足够的内存。
> 
> 虽然这个数字肯定取决于 GPU 卡，但对于 10GB GPU 是否有任何粗略的数字（例如，$2^20$ 限制）？
> 
> ### 3.多GPU用于FFT和multiexp
> 目前，内存不足时是否可以使用多 GPU 来支持更大的尺寸？ 看来目前实现独立使用许多小型FFT和multiexp每个GPU，根据[fft.cl](https://github.com/filecoin-project/bellperson/blob/master/src/gpu/fft/fft.cl)和[multiexp.cl](https://github.com/filecoin-project/bellperson/blob/master/src/gpu/multiexp/multiexp.cl)。
> 
> 谢谢！



> ### 1. Is there any official benchmark code for FFT on GPU?
> There is a one-line code for benchmarking multiexp on GPU
> 
> `RUST_LOG=info cargo test --features gpu -- --exact multiexp::gpu_multiexp_consistency --nocapture`
> 
> It shows that GPU is around 120x faster than the cpu version, when tested on a 3090 GPU.
> 
> Where can I find a similar one-line code for benchmarking FFT on GPU?
> 
> ### 2. What is the maximum number of constraints supported?
> As mentioned in the README, there is a certain upper bound on proof size (i.e., the number of constraints).
> 
> > Depending on the size of the proof being passed to the gpu for work, certain cards will not be able to allocate enough memory to either the FFT or Multiexp kernel.
> 
> While this number certainly depends on the GPU card, is there any rough number (e.g., $2^20$ constraints) for a 10GB GPU?
> 
> ### 3. Multi-GPU for FFT and multiexp
> Currently, could multi-gpu be used to support a larger size when out-of-memory? It seems the current implementation use each GPU independently for many small-size FFT and multiexp, according to [fft.cl](https://github.com/filecoin-project/bellperson/blob/master/src/gpu/fft/fft.cl) and [multiexp.cl](https://github.com/filecoin-project/bellperson/blob/master/src/gpu/multiexp/multiexp.cl).
> 
> Can you give me your contact information? Tg /email I would like to ask you some questions

> ### 1. Is there any official benchmark code for FFT on GPU?
> There is a one-line code for benchmarking multiexp on GPU
> 
> `RUST_LOG=info cargo test --features gpu -- --exact multiexp::gpu_multiexp_consistency --nocapture`
> 
> It shows that GPU is around 120x faster than the cpu version, when tested on a 3090 GPU.
> 
> Where can I find a similar one-line code for benchmarking FFT on GPU?
> 
> ### 2. What is the maximum number of constraints supported?
> As mentioned in the README, there is a certain upper bound on proof size (i.e., the number of constraints).
> 
> > Depending on the size of the proof being passed to the gpu for work, certain cards will not be able to allocate enough memory to either the FFT or Multiexp kernel.
> 
> While this number certainly depends on the GPU card, is there any rough number (e.g., $2^20$ constraints) for a 10GB GPU?
> 
> ### 3. Multi-GPU for FFT and multiexp
> Currently, could multi-gpu be used to support a larger size when out-of-memory? It seems the current implementation use each GPU independently for many small-size FFT and multiexp, according to [fft.cl](https://github.com/filecoin-project/bellperson/blob/master/src/gpu/fft/fft.cl) and [multiexp.cl](https://github.com/filecoin-project/bellperson/blob/master/src/gpu/multiexp/multiexp.cl).
> 
> Thanks!

Can you give me your contact information? Tg /email . I would like to ask you some questions

**Comment by vmx** [comment]
> Where can I find a similar one-line code for benchmarking FFT on GPU?

There is a similar benchmark to the Multiexp one for FFT in [`domain.rs`](https://github.com/filecoin-project/bellperson/blob/master/src/domain.rs#L545). You should be able to run it as:

    RUST_LOG=info cargo test --features opencl -- gpu_fft_consistency --nocapture

Please note that instead of `--features opencl`, you could also try the experimental `--features cuda`, that should even be faster on nvidia cards.
