### ISSUE TITLE
run proof.synthesize in parallel

### ISSUE THREAD

**Issue by fishjar** [filecoin-project/bellperson#223]
I try to run proof.synthesize in parallel, but got an error while verify_seal:

```sh
porep proof for sector 0 was invalid:
```

**Comment by dignifiedquire** [comment]
It is not possible to easily parallelize synthesis of porep today.

**Comment by fishjar** [comment]
Sad to hear this answer. I think solving this problem is the key to optimizing C2.
Is it possible in the future?
