### ISSUE TITLE
bellperson 0.18 fails to build with nvcc

### ISSUE THREAD

**Issue by Krysme** [filecoin-project/bellperson#241]
Here is the function that fails to compile

```
KERNEL void radix_fft(GLOBAL Fr* x, // Source buffer
                      GLOBAL Fr* y, // Destination buffer
                      GLOBAL Fr* pq, // Precalculated twiddle factors
                      GLOBAL Fr* omegas, // [omega, omega^2, omega^4, ...]
                      LOCAL Fr* u_arg, // Local buffer to store intermediary values
                      uint n, // Number of elements
                      uint lgp, // Log2 of `p` (Read more in the link above)
                      uint deg, // 1=>radix2, 2=>radix4, 3=>radix8, ...
                      uint max_deg) // Maximum degree supported, according to `pq` and `omegas`
{
```

The 5th argument is marked as "LOCAL", and in the case of CUDA, "LOCAL" is defined as "__shared__", and then I got this error message that this argument cannot be "shared" from the `nvcc` compiler.

Is there any workaround that can be done to it so I can compile it with CUDA?

**Comment by vmx** [comment]
Things should compile fine when the `cuda` feature enabled (`cargo build --features cuda`)? Can you please post the full command you are running and the console output of it.

**Comment by Krysme** [comment]
> Things should compile fine when the `cuda` feature enabled (`cargo build --features cuda`)? Can you please post the full command you are running and the console output of it.

Alright, now I just figured it out. The version of `nvcc` is 9 instead of 11. It compiles with V11.5, so, I believe this issue shall be closed.

**Comment by vmx** [comment]
Perfect, thanks for the clarification.
