### ISSUE TITLE
Dedicated GPU for WinningPoSt

### ISSUE THREAD

**Issue by vmx** [filecoin-project/bellperson#251]
If a system has more than one GPU, there could be a setting to dedicate a GPU just to run WinningPoSts. If there is no such proof, the GPU will be idle. Only the other GPUs will be used to run other proofs.

This idea is based on discussions with @cryptonemo and @DrPeterVanNostrand and were triggered by https://github.com/filecoin-project/bellperson/pull/246.

**Comment by phoenixzhua** [comment]
Actually it tried to solve a issue that GPU is locked during WindowPoSt.
 
If a system has only one GPU, we just set the env. variable: WINPOST_TMPDIR for the GPU locked file of WinningPoSts. And WinningPoSts and WindowPoSts could be doing at the same time. 

As long as the GPU have enough power and ram, we could win the block reward during WindowPoSt. I have tested that situation on calibration net with only one GPU.

**Comment by phoenixzhua** [comment]
If a system has more than one GPU, I would suggest to dedicate a GPU just to run WinningPoSts, to ensure the WinningPoSt has enough GPU resource to win the block reward.

**Comment by vmx** [comment]
In regards to single GPU usage: The current code prioritizes PoSts over PoReps. Though indeed it doesn't make a distinction between WindowPoSt and WindowPoSt and only one of them can run on the GPU at a given time. Adding support for running several proofs at the same time is tricky and I currently don't think it will be supported in the near future.

**Comment by vmx** [comment]
This can be solved on a higher level. You can have two separate Lotus workers where each of them is using a different GPU (e.g. via `CUDA_VISIBLE_DEVICES`) and different `TMPDIR`s. One worker would do WindowPoSts, the other would do WinningPoSts.
