### ISSUE TITLE
Multi Cuda Stream Support in Bellperson?

### ISSUE THREAD

**Issue by ProgramAPE** [filecoin-project/bellperson#252]
Is there a plan to add multi streams to Cuda implementation ?
I read the Cuda doc and it says multi streams can decrease the computation time.

**Comment by vmx** [comment]
What we currently run on the GPU is really sequential. We currently even do things synchronously as doing it asynchronously didn't make any difference. So AFAICT there won't be any benefit of using multiple streams.

**Comment by ProgramAPE** [comment]
I Got it Thanks!
