### ISSUE TITLE
 failed to select a version for the requirement `funty = "~1.2"

### ISSUE THREAD

**Issue by 20171759** [filecoin-project/bellperson#285]
I noticed funty 1.2.0 get yanked, however, the projects has a transient dependency on bitvec 0.22 which requires funty="~1.2"。
![image](https://user-images.githubusercontent.com/57170238/202443943-760993f1-2753-46ef-b4ff-13b538bf8a90.png)。
I wonder if there is a solution to this problem?

**Comment by vmx** [comment]
If you have a Cargo.lock somewhere, you can use that. Or you can use https://github.com/filecoin-project/bellperson/pull/284.

**Comment by vmx** [comment]
Please try the latest version. If you still run into problems, feel free to re-open this issue.
