### ISSUE TITLE
update `ff` and `group` to 0.13

### ISSUE THREAD

**Issue by leonardoalt** [filecoin-project/bellperson#299]
Hi! `ff` 0.13 has been released a few months ago and is already used by other libraries such as https://github.com/zcash/pasta_curves and https://github.com/privacy-scaling-explorations/halo2curves. In order to make integration of different components easier, would it be fine for `bellperson` to also bump its `ff` version? I tried to do it myself, but got stuck while bumping `blstrs` which also needs to be done, so wanted to ask here. Thanks!

**Comment by vmx** [comment]
As we use `bellperson` within `rust-fil-proofs`, upgrading `ff` (and `group`) is a lot of work. It needs major versions for `ec-gpu-gen`, `bellperson`, `bstrs`, `bls-signatures` and `neptune`.

Help is appreciated and at one point we will upgrade (I had hoped we can wait for the next `group` release, as it likely will contain fixes that makes `ec-gpu-gen` better. But it might not be worth waiting for it). I can't say when we will upgrade, but having PRs ready would be great.

**Comment by leonardoalt** [comment]
Yea makes sense. I did upgrade it for `bellperson` while making `ec-gpu-gen` available only for tests (+ some other changes) since I personally don't need the functionality. I also upgraded it for `neptune`, `pasta-msm` and `fil-pasta-curves`. `blstrs` feels a lot more complicated, at least for me, since I don't have the prime fields information. I'll link my forks here and we can see if which PR sequence make sense, especially because of the dependency tree.

**Comment by vmx** [comment]
BTW: `fil-pasta-curves` should no longer be needed. It's a temporary fork to have the most recent features, while still being on the old `ff` and `group` versions. With this upgrade, it should be possible to use upstream `pasta-curves`.

**Comment by leonardoalt** [comment]
I just organized everything in my forks. In order of dependency:
- ec-gpu: https://github.com/leonardoalt/ec-gpu/pull/1
- bellperson: https://github.com/leonardoalt/bellperson/pull/1
- neptune: https://github.com/leonardoalt/neptune/pull/1 and https://github.com/leonardoalt/neptune/pull/2
For Neptune I confirm that using `pasta-curves 0.5.0` works instead of `fil-pasta-curves`.

`blstrs` and the remaining parts of `ec-gpu` are still going to be some work, but I think it should be fine for someone that is familiar with the libs, since some specific information is needed.

**Comment by vmx** [comment]
Thanks a lot! I can take care of `blstrs` and `ec-gpu`.

**Comment by huitseeker** [comment]
@vmx Happy to help with neptune as soon as you want.

**Comment by vmx** [comment]
This was fixed by https://github.com/filecoin-project/bellperson/pull/304. Thanks @leonardoalt for the initial work!
