### ISSUE TITLE
I am compiling this project in AWS cloud Instance p3.4x large that has V100 GPU and Cuda12.2 I always see this error "error: gpu tools error: cuda error: no kernel image is available for execution on the device"

### ISSUE THREAD

**Issue by shahzadATintel** [filecoin-project/bellperson#318]
I am trying to run this project using V100 GPU in AWS cloud, the instance I am using is p3.4x large. After compiling and running all the tests, for MSM test I am always seeing this error:
error: gpu tools error: cuda error: no kernel image is available for execution on the device

**Comment by vmx** [comment]
It looks like that a [Tesla V100 is the Volta architecture](https://www.techpowerup.com/gpu-specs/?architecture=Volta&sort=generation). Only Turing and newer is supported by bellperson.

**Comment by vmx** [comment]
I've opened https://github.com/filecoin-project/bellperson/pull/319 to make this clearer.
