### ISSUE TITLE
FFT error

### ISSUE THREAD

**Issue by deltazxm** [filecoin-project/bellperson#91]
128GB mem+128GB swap+2080Ti,V27
[2020-06-22T15:23:20.959][^[[33mWARN^[[0m][bellperson::domain:572] Cannot instantiate GPU FFT kernel! Error: Ocl Error:

################################ OPENCL ERROR ###############################

Error executing function: clCreateContext

Status error code: CL_OUT_OF_HOST_MEMORY (-6)

Please visit the following url for more information:

https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clCreateContext.html#errors

#############################################################################

**Comment by vmx** [comment]
We switched to a different OpenCL library in the meantime, hence I don't think that's a problem anymore. If you still run into this issue, feel free to re-open this issue with providing additional details.
